# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  

  config.vm.define "master" do |master|
    config.vm.provider :virtualbox do |v|
      v.memory = 1500
      v.cpus = 2
    end
    master.vm.box = "centos/7"
    master.vm.hostname = "master"
    master.vm.network :private_network, ip: '192.168.10.10'
  end

  config.vm.define "worker1" do |worker1|
    config.vm.provider :virtualbox do |v|
      v.memory = 512
      v.cpus = 2
    end
    worker1.vm.box = "centos/7"
    worker1.vm.hostname = "worker1"
    worker1.vm.network :private_network, ip: '192.168.10.11'
  end
  config.vm.define "worker2" do |worker2|
    config.vm.provider :virtualbox do |v|
      v.memory = 512
      v.cpus = 2
    end
    worker2.vm.box = "centos/7"
    worker2.vm.hostname = "worker2"
    worker2.vm.network :private_network, ip: '192.168.10.12'
  end

  config.vm.provision "shell" do |shell|
    shell.path = "./files/sshd_cfg.sh"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbooks/kuber.yml"
    ansible.inventory_path ="hosts"
  
    #ansible.verbose = true
  end

end
